version: '2'
services:
  web:
    build: .
    ports:
     - "8081:8081"
    links:
      - postgres
  postgres:
    build: ./database/
    volumes: 
      - $PWD/data:/var/lib/postgresql/data
      - ./database/init.sh:/docker-entrypoint-initdb.d/zinitdb.sh